--- 
jobs: 
  build: 
    branches: 
      only: 
        - source
    docker: 
      - 
        image: "circleci/node:8.11-stretch-browsers"
    steps: 
      - checkout
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"package.json\" }}"
            - v1-dependencies-
      - 
        run: 
          command: "yarn install\n"
          name: "Install Dependencies"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"package.json\" }}"
          paths: 
            - node_modules
      - 
        run: 
          command: |
              git config --global user.email "$GH_EMAIL"
              git config --global user.name "$GH_NAME"
              npm run deploy
          name: "Build and Deploy"
    working_directory: ~/repo
version: 2
