version: 2

jobs:
  build:
    branches:
      only:
        - source
    docker:
       - image: circleci/node:8.11-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build and Deploy
          command: |
            git config --global user.email "$GH_EMAIL"
            git config --global user.name "$GH_NAME"
            npm run deploy
