version: 2

jobs:
  build:
    docker:
       - image: circleci/node:8.11-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build Pages
          command: |
            ./node_modules/.bin/gatsby build
            cp -a public/. out/.

            mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
            cd out

            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

            git push origin gh-pages