version: 2

jobs:
  build:
    docker:
       - image: circleci/node:8.11-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build and Deploy Pages
          command: |
            git config user.email "varunnotkar59@gmail.com"
            git config user.name "varun"
            npm run deploy
